# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.AutoField(db_column=b'idEstudio', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column=b'estudio', max_length=200, verbose_name=b'Descripcion')),
                ('codigoMedico', models.CharField(max_length=50)),
                ('abreviatura', models.CharField(max_length=20)),
                ('usedLevel', models.IntegerField()),
            ],
            options={
                'ordering': ['descripcion'],
                'db_table': 'AlmacenEstudios',
            },
        ),
    ]
