# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-06-10 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica', '0002_auto_20190107_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='porcentaje_medico',
            field=models.IntegerField(db_column=b'porcentajeMedico', default=0),
        ),
    ]
