# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 16:04


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField()),
                ('nombre', models.CharField(db_column='nombres', max_length=200, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido')),
                ('edad', models.IntegerField()),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('domicilio', models.CharField(db_column='direccion', max_length=200, verbose_name='Domicilio')),
                ('telefono', models.CharField(db_column='tel', max_length=200, verbose_name='Telefono')),
                ('sexo', models.CharField(max_length=50)),
                ('nroAfiliado', models.CharField(max_length=200, verbose_name='Nro')),
                ('email', models.CharField(db_column='e_mail', max_length=200, verbose_name='Email')),
            ],
            options={
                'db_table': 'tblPacientes',
            },
        ),
    ]
