# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-04-22 07:24


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20190107_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[(b'Masculino','Masculino'), (b'Femenino','Femenino')], max_length=50),
        ),
    ]
