# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-06-10 07:09


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20200422_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='informacion_extra',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Informacion Extra'),
        ),
    ]
