# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        ('obra_social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anestesista',
            fields=[
                ('id', models.AutoField(db_column='idMedicoAn', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombreMedicoAn', max_length=200, verbose_name='Nombre')),
                ('apellido', models.CharField(db_column='apellidoMedicoAn', max_length=200, verbose_name='Apellido')),
                ('matricula', models.CharField(blank=True, db_column='nroMatricula', max_length=200, null=True, verbose_name='Matricula')),
                ('direccion', models.CharField(blank=True, db_column='direccionMedico', max_length=200, null=True, verbose_name='Direccion')),
                ('localidad', models.CharField(blank=True, db_column='localidadMedico', max_length=200, null=True, verbose_name='Localidad')),
                ('telefono', models.CharField(blank=True, db_column='telMedico', max_length=200, null=True, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, db_column='mail', max_length=200, null=True, verbose_name='E-mail')),
            ],
            options={
                'ordering': ['apellido'],
                'db_table': 'tblMedicosAnestesistas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Complejidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'tblComplejidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComplejidadEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudios', models.CharField(blank=True, max_length=500, null=True)),
                ('formula', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tblComplejidadEstudios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LineaPagoAnestesista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_paciente_diferenciado', models.BooleanField()),
                ('formula', models.CharField(max_length=200)),
                ('formula_valorizada', models.CharField(max_length=500)),
                ('importe', models.DecimalField(decimal_places=2, default='0.00', max_digits=16)),
                ('alicuota_iva', models.DecimalField(decimal_places=2, default='0.00', max_digits=16)),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obra_social.ObraSocial')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PagoAnestesista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('anestesista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anestesista.Anestesista')),
            ],
        ),
        migrations.AddField(
            model_name='lineapagoanestesista',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='anestesista.PagoAnestesista'),
        ),
    ]
