# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-11 21:24


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anestesista', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='anestesista',
            table='tblMedicosAnestesistas',
        ),
    ]
