# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-23 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0003_auto_20170118_2013'),
        ('anestesista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapagoanestesista',
            name='estudios',
            field=models.ManyToManyField(to='estudio.Estudio'),
        ),
    ]
