# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-10 18:46


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Anestesista',
        # ),
    ]
