# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-01-07 16:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_delete_anestesista'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='clave_fiscal',
            field=models.CharField(blank=True, db_column='claveFiscal', default='', max_length=200, verbose_name='Clave Fiscal'),
        ),
        migrations.AddField(
            model_name='medico',
            name='domicilio',
            field=models.CharField(blank=True, db_column='direccionMedico', max_length=200, verbose_name='Domicilio'),
        ),
        migrations.AddField(
            model_name='medico',
            name='localidad',
            field=models.CharField(blank=True, db_column='localidadMedico', max_length=200, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='medico',
            name='mail',
            field=models.CharField(blank=True, db_column='mail', max_length=200, verbose_name='Mail'),
        ),
        migrations.AddField(
            model_name='medico',
            name='matricula',
            field=models.CharField(blank=True, db_column='nroMatricula', max_length=200, verbose_name='Matr\xc3\xadcula'),
        ),
        migrations.AddField(
            model_name='medico',
            name='responsabilidad_fiscal',
            field=models.CharField(choices=[(b'INSCRIPTO','INSCRIPTO'), (b'MONOTRIBUTO','MONOTRIBUTO')], db_column='responsabilidadFiscal', default='MONOTRIBUTO', max_length=200, verbose_name='Responsabilidad Fiscal'),
        ),
        migrations.AddField(
            model_name='medico',
            name='telefono',
            field=models.CharField(blank=True, db_column='telMedico', max_length=200, verbose_name='Tel\xc3\xa9fono'),
        ),
    ]
