# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-04-03 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_auto_20190107_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='facturar_amr_en_nombre_de_medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturar_amr_medico', to='medico.Medico'),
        ),
        migrations.AddField(
            model_name='medico',
            name='facturar_osde_en_nombre_de_medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturar_osde_medico', to='medico.Medico'),
        ),
    ]
