# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-01-07 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra_social', '0002_obrasocial_se_presenta_por_ara'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasocial',
            name='codigo_postal',
            field=models.IntegerField(blank=True, db_column=b'codigoPostal', default=b'', verbose_name='C\xf3digo Postal'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='condicion_fiscal',
            field=models.CharField(choices=[(b'CONSUMIDOR FINAL', b'CONSUMIDOR FINAL'), (b'RESPONSABLE INSCRIPTO', b'RESPONSABLE INSCRIPTO'), (b'EXENTO', b'EXENTO')], db_column=b'condicionFiscal', default=b'CONSUMIDOR FINAL', max_length=200, verbose_name='Condici\xf3n Fiscal'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='direccion',
            field=models.CharField(blank=True, db_column='direccion', default=b'', max_length=200, verbose_name='Direcci\xf3n'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='localidad',
            field=models.CharField(blank=True, db_column=b'localidad', default=b'', max_length=200, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='observaciones',
            field=models.TextField(blank=True, db_column=b'observaciones', verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='se_presenta_por_AMR',
            field=models.CharField(choices=[(b'1', b'Si'), (b'0', b'No')], db_column=b'sePresentaPorAMR', default=0, max_length=200, verbose_name='Se presenta por AMR'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='telefono',
            field=models.CharField(blank=True, db_column=b'telefono', default=b'', max_length=200, verbose_name='Tel\xe9fono'),
        ),
        migrations.AlterField(
            model_name='obrasocial',
            name='se_presenta_por_ARA',
            field=models.CharField(choices=[(b'1', b'Si'), (b'0', b'No')], db_column=b'sePresentaPorARA', default=0, max_length=200, verbose_name='Se presenta por ARA'),
        ),
    ]
