# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-01-15 20:10


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra_social', '0002_obrasocial_se_presenta_por_ara'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasocial',
            name='codigo_postal',
            field=models.IntegerField(blank=True, db_column='codigoPostal', default=0, verbose_name='C\xf3digo Postal'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='condicion_fiscal',
            field=models.CharField(choices=[(b'CONSUMIDOR FINAL','CONSUMIDOR FINAL'), (b'RESPONSABLE INSCRIPTO','RESPONSABLE INSCRIPTO'), (b'EXENTO','EXENTO')], db_column='condicionFiscal', default='CONSUMIDOR FINAL', max_length=200, verbose_name='Condici\xf3n Fiscal'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='direccion',
            field=models.CharField(blank=True, db_column='direccion', default='', max_length=200, verbose_name='Direcci\xf3n'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='localidad',
            field=models.CharField(blank=True, db_column='localidad', default='', max_length=200, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='observaciones',
            field=models.TextField(blank=True, db_column='observaciones', verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='se_presenta_por_AMR',
            field=models.CharField(choices=[(b'1','Si'), (b'0','No')], db_column='sePresentaPorAMR', default=0, max_length=200, verbose_name='Se presenta por AMR'),
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='telefono',
            field=models.CharField(blank=True, db_column='telefono', default='', max_length=200, verbose_name='Tel\xe9fono'),
        ),
        migrations.AlterField(
            model_name='obrasocial',
            name='se_presenta_por_ARA',
            field=models.CharField(choices=[(b'1','Si'), (b'0','No')], db_column='sePresentaPorARA', default=0, max_length=200, verbose_name='Se presenta por ARA'),
        ),
    ]
