# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-09-09 17:19


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practica', '0002_auto_20190107_1629'),
        ('obra_social', '0003_auto_20190115_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArancelObraSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(db_column='Precio', decimal_places=2, max_digits=16)),
                ('precio_anestesia', models.DecimalField(db_column='precioAnestesia', decimal_places=2, max_digits=16)),
                ('fecha', models.DateField()),
                ('obra_social', models.ForeignKey(db_column='idObraSocial', on_delete=django.db.models.deletion.CASCADE, to='obra_social.ObraSocial')),
                ('practica', models.ForeignKey(db_column='idEstudio', on_delete=django.db.models.deletion.CASCADE, to='practica.Practica')),
            ],
            options={
                'db_table': 'AlmacenPreciosEstOS',
            },
        ),
        migrations.AlterUniqueTogether(
            name='arancelobrasocial',
            unique_together=set([('practica', 'obra_social')]),
        ),
    ]
