# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-10-31 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra_social', '0004_auto_20190909_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasocial',
            name='valor_aproximado_pension',
            field=models.DecimalField(db_column='valorAproximadoPension', decimal_places=2, default=0, max_digits=10, verbose_name='Valor Aproximado Pension'),
        ),
    ]
