# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-12-23 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra_social', '0005_obrasocial_valor_aproximado_pension'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasocial',
            name='nro_cuit',
            field=models.CharField(db_column=b'nroCuit', default=b'', max_length=200, verbose_name='CUIT'),
        ),
    ]
