# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-12-23 14:41


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante', '0002_auto_20170724_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='fecha_recepcion',
            field=models.DateField(db_column='fechaRecepcion', null=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='gravado_paciente',
            field=models.CharField(db_column='gravadoPaciente', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='total_cobrado',
            field=models.DecimalField(db_column='totalCobrado', decimal_places=2, max_digits=16, null=True),
        ),
    ]
