# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-10 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante', '0003_auto_20191223_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineadecomprobante',
            name='concepto',
            field=models.CharField(max_length=1000),
        ),
    ]
