# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='stock',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
