# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-27 20:22


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0002_auto_20161129_1944'),
        ('medicamento', '0002_auto_20161125_2025'),
    ]

    operations = [
    ]
