# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-01-07 16:29
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0003_merge_20170127_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='importe',
            field=models.DecimalField(db_column='importeMedicamento', decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
    ]
