# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 16:04


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comprobante', '0001_initial'),
        ('obra_social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoPresentacion',
            fields=[
                ('id', models.AutoField(db_column='idPagoFact', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='fechaPagoFact', verbose_name='Fecha')),
                ('nro_recivo', models.CharField(db_column='nroRecivo', max_length=128)),
                ('importe', models.FloatField(db_column='importePago')),
                ('gasto_administrativo', models.FloatField(db_column='gastoAdministrativo', default='0')),
            ],
            options={
                'db_table': 'tblPagoFacturacion',
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(db_column='idFacturacion', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='fechaFacturacion', verbose_name='Fecha')),
                ('estado', models.SmallIntegerField(choices=[(0,'Pendiente'), (1,'Cobrado'), (2,'Abierto')], db_column='pagado')),
                ('periodo', models.CharField(max_length=128)),
                ('iva', models.FloatField()),
                ('total', models.FloatField(default='0')),
                ('total_facturado', models.FloatField(db_column='totalFacturado', default='0')),
                ('comprobante', models.ForeignKey(db_column='idComprobante', on_delete=django.db.models.deletion.CASCADE, to='comprobante.Comprobante')),
                ('obra_social', models.ForeignKey(db_column='idObraSocial', on_delete=django.db.models.deletion.CASCADE, to='obra_social.ObraSocial')),
            ],
            options={
                'db_table': 'tblFacturacion',
            },
        ),
        migrations.AddField(
            model_name='pagopresentacion',
            name='presentacion',
            field=models.ForeignKey(db_column='idFacturacion', on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='presentacion.Presentacion'),
        ),
    ]
