# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-01-24 01:14
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentacion', '0002_auto_20190107_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagopresentacion',
            name='gasto_administrativo',
            field=models.DecimalField(db_column='gastoAdministrativo', decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='pagopresentacion',
            name='importe',
            field=models.DecimalField(db_column='importePago', decimal_places=2, max_digits=16),
        ),
    ]
