# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-01-03 11:06


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentacion', '0003_auto_20190124_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacion',
            name='comprobante',
            field=models.ForeignKey(db_column='idComprobante', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presentacion', to='comprobante.Comprobante'),
        ),
    ]
