# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-04-24 15:06


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentacion', '0004_auto_20200103_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacion',
            name='sucursal',
            field=models.IntegerField(choices=[(1,'Cedir'), (2,'Hospital Italiano')], default=1, verbose_name='Sucursal'),
        ),
    ]
