# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-05-04 01:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentacion', '0005_presentacion_sucursal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagopresentacion',
            old_name='nro_recivo',
            new_name='nro_recibo',
        ),
        migrations.RenameField(
            model_name='pagopresentacion',
            old_name='gasto_administrativo',
            new_name='retencion_impositiva',
        ),
    ]
