# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 16:04


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Resumen')),
                ('body', models.TextField(blank=True, verbose_name='Desarrollo')),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('publishInitDate', models.DateField(blank=True, null=True, verbose_name='Inicio de publicacion')),
                ('publishEndDate', models.DateField(blank=True, null=True, verbose_name='Fin de publicacion')),
                ('publishContent', models.BooleanField(default=True, verbose_name='Publicar contenido')),
                ('destacarContent', models.BooleanField(default=False, verbose_name='Destacar contenido')),
                ('img1', models.ImageField(blank=True, upload_to='uploads_imgs', verbose_name='Imagen principal')),
                ('img2', models.ImageField(blank=True, upload_to='uploads_imgs', verbose_name='Imagen 2')),
                ('img3', models.ImageField(blank=True, upload_to='uploads_imgs', verbose_name='Imagen 3')),
                ('footer', models.TextField(blank=True, verbose_name='Pie')),
                ('friendlyURL', models.CharField(blank=True, max_length=100, null=True, verbose_name='Friendly URL')),
                ('categoria', models.ManyToManyField(to='contenidos.Categoria', verbose_name='Categoria')),
            ],
        ),
    ]
