# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 18:36


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0004_contenidos_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido',
            name='created',
        ),
        migrations.AddField(
            model_name='contenido',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
