# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudio',
            old_name='medicoSolicitante',
            new_name='medico_solicitante',
        ),
        migrations.RenameField(
            model_name='estudio',
            old_name='obraSocial',
            new_name='obra_social',
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='arancelAnestesia',
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='diferenciaPaciente',
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='esPagoContraFactura',
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='fechaCobro',
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='importeCobradoArancelAnestesia',
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='importeCobradoPension',
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='importeEstudio',
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='importeEstudioCobrado',
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='importeMedicacion',
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='importeMedicacionCobrado',
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='motivoEstudio',
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='nroDeOrden',
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='pagoContraFactura',
        ),
        migrations.AddField(
            model_name='estudio',
            name='arancel_anestesia',
            field=models.FloatField(db_column=b'arancelAnestesia', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudio',
            name='diferencia_paciente',
            field=models.FloatField(db_column=b'diferenciaPaciente', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudio',
            name='es_pago_contra_factura',
            field=models.IntegerField(db_column=b'esPagoContraFactura', default=0),
        ),
        migrations.AddField(
            model_name='estudio',
            name='fecha_cobro',
            field=models.CharField(db_column=b'fechaCobro', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='importe_cobrado_arancel_anestesia',
            field=models.FloatField(db_column=b'importeCobradoArancelAnestesia', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudio',
            name='importe_cobrado_pension',
            field=models.FloatField(db_column=b'importeCobradoPension', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudio',
            name='importe_estudio',
            field=models.FloatField(db_column=b'importeEstudio', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudio',
            name='importe_estudio_cobrado',
            field=models.FloatField(db_column=b'importeEstudioCobrado', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudio',
            name='importe_medicacion',
            field=models.FloatField(db_column=b'importeMedicacion', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudio',
            name='importe_medicacion_cobrado',
            field=models.FloatField(db_column=b'importeMedicacionCobrado', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudio',
            name='motivo',
            field=models.CharField(blank=True, db_column=b'motivoEstudio', max_length=300, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='nro_de_orden',
            field=models.CharField(db_column='nroDeOrden', default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudio',
            name='pago_contra_factura',
            field=models.FloatField(db_column=b'pagoContraFactura', default=0),
            preserve_default=False,
        ),
    ]
