# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-18 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0002_auto_20161125_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='anestesista',
            field=models.ForeignKey(db_column=b'idAnestesista', on_delete=django.db.models.deletion.CASCADE, related_name='anestesista', to='anestesista.Anestesista'),
        ),
    ]
