# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-02-29 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0005_auto_20190805_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='sucursal',
            field=models.IntegerField(choices=[(1, b'Cedir'), (2, b'Hospital Italiano')], db_column=b'sucursal', default=1, verbose_name='Sucursal'),
        ),
    ]
