# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-02-19 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0006_estudio_lugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudio',
            name='lugar',
        ),
        migrations.AddField(
            model_name='estudio',
            name='institucion',
            field=models.IntegerField(db_column=b'institucion', default=1, verbose_name='Institucion'),
        ),
    ]
