# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 16:04


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medico', '0001_initial'),
        ('paciente', '0001_initial'),
        ('obra_social', '0001_initial'),
        ('practica', '0001_initial'),
        ('sala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'turnos_estados',
            },
        ),
        migrations.CreateModel(
            name='InfoTurno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medico.Medico')),
                ('obra_sociales', models.ManyToManyField(blank=True, to='obra_social.ObraSocial')),
                ('practicas', models.ManyToManyField(blank=True, to='practica.Practica')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_otorgamiento', models.DateTimeField(verbose_name='Fecha Otorgamiento')),
                ('fechaTurno', models.DateField(verbose_name='Fecha Turno')),
                ('horaInicio', models.TimeField(verbose_name='Hora Inicio')),
                ('horaFinEstimada', models.TimeField(verbose_name='Hora Fin Estimada')),
                ('horaFinReal', models.TimeField(verbose_name='Hora Fin Real')),
                ('observacion', models.CharField(blank=True, max_length=200, verbose_name='Observacion')),
                ('estado', models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.CASCADE, to='turno.Estado')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.Medico')),
                ('obraSocial', models.ForeignKey(db_column='idObraSocial', on_delete=django.db.models.deletion.CASCADE, to='obra_social.ObraSocial')),
                ('paciente', models.ForeignKey(db_column='idPaciente', on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
                ('practicas', models.ManyToManyField(to='practica.Practica')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala.Sala')),
            ],
            options={
                'db_table': 'turnos_turnos',
            },
        ),
    ]
