# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-01-06 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0002_fechanoatencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechanoatencion',
            name='medico',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='medico.Medico'),
        ),
    ]
