# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-02-10 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudio', '0004_auto_20190107_1629'),
        ('medico', '0003_auto_20190107_1629'),
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='estudio',
            field=models.ForeignKey(blank=True, db_column=b'nroEstudio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja', to='estudio.Estudio'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='medico',
            field=models.ForeignKey(blank=True, db_column=b'idMedico', null=True, on_delete=django.db.models.deletion.CASCADE, to='medico.Medico'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='monto_acumulado',
            field=models.DecimalField(blank=True, db_column=b'montoAcumulado', decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='tipo',
            field=models.ForeignKey(blank=True, db_column=b'idTipoDeMovimiento', null=True, on_delete=django.db.models.deletion.CASCADE, to='caja.TipoMovimientoCaja'),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
