# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-08-25 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_auto_20190210_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='concepto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='monto_acumulado',
            field=models.DecimalField(db_column=b'montoAcumulado', decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='tipo',
            field=models.ForeignKey(db_column=b'idTipoDeMovimiento', on_delete=django.db.models.deletion.CASCADE, to='caja.TipoMovimientoCaja'),
        ),
    ]
