# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-08-06 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_auto_20190210_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='estado',
            field=models.NullBooleanField(choices=[(None, b'-'), (True, b'Si'), (False, b'No')], verbose_name=b'Pagado'),
        ),
    ]
